source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-partial'
gem 'thin'
gem 'omniauth'
gem 'omniauth-salesforce', :git => 'https://github.com/realdoug/omniauth-salesforce.git'
gem 'databasedotcom'
gem 'haml'
gem 'sass'
